version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - mynetwork

  app:
    image: api
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    ports:
      - 8085:8085
    environment:
      - DB_HOST=mongodb
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=weatherRisk_db
      - DB_PORT=27017
    stdin_open: true
    tty: true
    networks:
      - mynetwork

volumes:
  db:

networks:
  mynetwork:
